---
apiVersion: v1
kind: ReplicationController
metadata:
  name: version-app-rc
spec:
  replicas: 3
  selector:
    app: version-app
  template:
    metadata:
      labels:
        app: version-app
    spec:
      containers:
      - name: version-app
        image: pyphercises/app:v3.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
          name: vapp-port